test_jeet/myapp/urls.py
from django.urls import path

from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('registration/', views.UserRegistration.as_view(), name='registration'),
]

test_jeet/test_jeet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),

]

test_jeet/myapp/models.py
from django.db import models


# Create your models here.

class Registration(models.Model):
	name = models.CharField(max_length = 25)
	email = models.CharField(max_length=30)
	contact = models.IntegerField(11)
	gender = models.CharField(max_length=5)
	
	def __str__(self):
		return self.name


class Address(models.Model):

	user_address = models.CharField(max_length = 50)
	country = models.CharField(max_length=25)
	state = models.CharField(max_length=25)
	city = models.CharField(max_length=25)
	registration = models.ForeignKey(Registration,on_delete = models.CASCADE)
	delete = models.IntegerField(5)

	def __str__(self):
		return self.user_address


 
	 
    

test_jeet/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.views import View
from django.shortcuts import render_to_response
from myapp.models import Registration
from django.template import RequestContext

class IndexView(ListView):
	context_object_name = 'user_list'
	template_name = 'myapp/index.html'
	def get_queryset(self):
		return Registration.objects.all()

class DetailView(DetailView):
	
	model = Registration
	template_name ='myapp/detail.html'


class UserRegistration(View):
	template_name ='myapp/create.html'
	model = Registration
	# fields = ['name','email', 'contact', 'gender','delete']

	def get(self,request,*args,**kwargs):
		return render(request,self.template_name)
		# return HttpResponse('testing')
	def post(self,required,*args,**kwargs):
		print('gagan')
		name = required.POST['name']
		email = required.POST['email']
		contact = required.POST['contact']
		gender = required.POST['gender']
		instance = Registration(name=name, email=email,contact=contact,gender=gender);
		instance.save()
		# import ipdb;ipdb.set_trace()
		return HttpResponse(email)	
	

test_jeet/myapp/templates/myapp/create.html
<!DOCTYPE html>
<html>
<head>
	<title>User Registration</title>
</head>
<body>
	<form method="POST" action="{% url 'myapp:registration'%}">
		{% csrf_token %}
	<center>
		Name:<input type="text" name="name">
		<br><br>Email:<input type="text" name="email">
		<br><br>Gender:<input type="text" name="gender">
		<br><br>Contact:<input type="text" name="contact"><br><br>
	     <input type="submit" value="Save">
    </center>
	</form>

</body>
</html>

test_jeet/myapp/templates/myapp/detail.html
<center>

<form method="post" action="">

	
	<input type="text" name="name" value="{{registration.name}}"> <br><br>
	<input type="text" name="email" value="{{registration.email}}"><br><br>
	<input type="text" name="contact" value="{{registration.contact}}"><br><br>
	<input type="text" name="gen" value="{{registration.gender}}"><br><br>
	<input type="submit" name="submit" value="Update">
</form>
</center>

test_jeet/myapp/templates/myapp/index.html
<!DOCTYPE html>
<html>
<head>
	<title>MY Django Project</title>
</head>
<body>

	{% if user_list %}
	<table>
		<thead>
			<tr>
				<td> Name </td>
				<td> Email </td>
				<td> Contact </td>
				<td> Gender </td>
				<td> Action </td>

			</tr>
		</thead>
		<tbody>
			{% for users in user_list  %}
			<tr>
				<td> {{users.name}} </td>
				<td> {{users.email}} </td>
				<td> {{users.contact}} </td>
				<td> {{users.gender}} </td>
				<td> <a href="{% url 'myapp:detail' users.id %}"> Edit </a> </td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

	{% endif %}

</body>
</html>